In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings("ignore")

In [7]:
from sklearn.neighbors import LocalOutlierFactor
from sklearn.datasets import make_moons

X,y=make_moons(n_samples=300,noise=0.1)

In [8]:
X

array([[ 3.80847518e-01,  9.02496207e-01],
       [ 6.20395374e-01, -2.76209036e-01],
       [ 3.99802944e-01, -1.90698137e-01],
       [ 3.59725891e-01, -1.08460143e-01],
       [ 1.88049836e+00,  3.77472693e-02],
       [ 4.41138203e-01, -3.14641310e-01],
       [-1.05705488e+00,  1.53900831e-01],
       [ 1.12839836e-01,  5.03760871e-01],
       [ 9.65528672e-01,  2.76460054e-01],
       [-7.31058047e-01,  7.20280205e-01],
       [ 2.41508078e-01, -4.03240402e-03],
       [ 1.01274656e+00, -5.11373265e-02],
       [ 1.84633217e+00,  3.08768739e-01],
       [ 9.84943620e-02,  1.05281779e+00],
       [ 1.14561409e+00,  5.31870790e-01],
       [ 7.96113554e-01, -7.00620037e-01],
       [ 2.99387200e-01, -9.81484956e-02],
       [-5.03215406e-01,  7.51539763e-01],
       [ 1.24340085e+00, -2.84579671e-01],
       [ 8.80849372e-01,  3.82425412e-02],
       [-5.75170388e-01,  1.11372897e+00],
       [ 1.95017060e+00, -1.01172594e-01],
       [ 6.50076795e-02,  3.02409293e-02],
       [ 9.

In [9]:
y

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0], d

In [12]:
X_outliers=np.random.uniform(low=-3,high=3,size=(20,2))
x=np.vstack((X,X_outliers))

In [13]:
x

array([[ 3.80847518e-01,  9.02496207e-01],
       [ 6.20395374e-01, -2.76209036e-01],
       [ 3.99802944e-01, -1.90698137e-01],
       [ 3.59725891e-01, -1.08460143e-01],
       [ 1.88049836e+00,  3.77472693e-02],
       [ 4.41138203e-01, -3.14641310e-01],
       [-1.05705488e+00,  1.53900831e-01],
       [ 1.12839836e-01,  5.03760871e-01],
       [ 9.65528672e-01,  2.76460054e-01],
       [-7.31058047e-01,  7.20280205e-01],
       [ 2.41508078e-01, -4.03240402e-03],
       [ 1.01274656e+00, -5.11373265e-02],
       [ 1.84633217e+00,  3.08768739e-01],
       [ 9.84943620e-02,  1.05281779e+00],
       [ 1.14561409e+00,  5.31870790e-01],
       [ 7.96113554e-01, -7.00620037e-01],
       [ 2.99387200e-01, -9.81484956e-02],
       [-5.03215406e-01,  7.51539763e-01],
       [ 1.24340085e+00, -2.84579671e-01],
       [ 8.80849372e-01,  3.82425412e-02],
       [-5.75170388e-01,  1.11372897e+00],
       [ 1.95017060e+00, -1.01172594e-01],
       [ 6.50076795e-02,  3.02409293e-02],
       [ 9.

In [14]:
out=LocalOutlierFactor(n_neighbors=20,contamination=0.1)
y_pred=out.fit_predict(X)

In [15]:
y_pred

array([ 1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1,  1,
        1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,
        1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1