In [1]:
#data encoding >> converting categorical column to numeric
# nominal/OHE/dummay variable creation >> creation of dummy variable 
# label and ordinal encoding
# Target guide ordinal ecoding

In [6]:
#nominal/OHE >> binary vectors for each category

In [7]:
#Single,Married, a relationship
#Single >[1,0,0]
#Married >[0,1,0]
# in a relationship >[0,0,1]

In [8]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [11]:
df=pd.DataFrame({'status':['Single','Married','Single','in a relationship','single','Married']})

In [13]:
df

status
0             Single
1            Married
2             Single
3  in a relationship
4             single
5            Married

In [14]:
encoder=OneHotEncoder()
encoder

OneHotEncoder()

In [15]:
encoded=encoder.fit_transform(df[['status']]).toarray()

In [21]:
encoded

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [16]:
encoder.get_feature_names_out()

array(['status_Married', 'status_Single', 'status_in a relationship',
       'status_single'], dtype=object)

In [22]:
pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

status_Married  status_Single  status_in a relationship  status_single
0             0.0            1.0                       0.0            0.0
1             1.0            0.0                       0.0            0.0
2             0.0            1.0                       0.0            0.0
3             0.0            0.0                       1.0            0.0
4             0.0            0.0                       0.0            1.0
5             1.0            0.0                       0.0            0.0

In [23]:
df

status
0             Single
1            Married
2             Single
3  in a relationship
4             single
5            Married

In [18]:
#new data >> single
encoder.transform([['Single']]).toarray()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1., 0., 0.]])

In [19]:
encoder.transform([['Married']]).toarray()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0., 0.]])

In [24]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [25]:
encoder_df

status_Married  status_Single  status_in a relationship  status_single
0             0.0            1.0                       0.0            0.0
1             1.0            0.0                       0.0            0.0
2             0.0            1.0                       0.0            0.0
3             0.0            0.0                       1.0            0.0
4             0.0            0.0                       0.0            1.0
5             1.0            0.0                       0.0            0.0

In [26]:
final_df=pd.concat([df,encoder_df],axis=1)

In [27]:
final_df.drop(['status','status_Married'],axis=1,inplace=True)

In [28]:
final_df

status_Single  status_in a relationship  status_single
0            1.0                       0.0            0.0
1            0.0                       0.0            0.0
2            1.0                       0.0            0.0
3            0.0                       1.0            0.0
4            0.0                       0.0            1.0
5            0.0                       0.0            0.0

In [34]:
df

status
0             Single
1            Married
2             Single
3  in a relationship
4             single
5            Married

In [35]:
pd.get_dummies(df[['status']])

status_Married  status_Single  status_in a relationship  status_single
0           False           True                     False          False
1            True          False                     False          False
2           False           True                     False          False
3           False          False                      True          False
4           False          False                     False           True
5            True          False                     False          False

In [36]:
pd.get_dummies(df['status'],drop_first=True)

Single  in a relationship  single
0    True              False   False
1   False              False   False
2    True              False   False
3   False               True   False
4   False              False    True
5   False              False   False

In [29]:
#using pandas
pd.get_dummies(df['status'],drop_first=True,dtype='int')

Single  in a relationship  single
0       1                  0       0
1       0                  0       0
2       1                  0       0
3       0                  1       0
4       0                  0       1
5       0                  0       0

In [30]:
#internal homework

import seaborn as sns

In [31]:
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [32]:
# Label encoding >> assign unique label 
df

status
0             Single
1            Married
2             Single
3  in a relationship
4             single
5            Married

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
LabelEncoder=LabelEncoder()

In [35]:
LabelEncoder.fit_transform(df[['status']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 2, 3, 0])

In [36]:
df

status
0             Single
1            Married
2             Single
3  in a relationship
4             single
5            Married

In [37]:
# ordinal encoding
# high school >> 1
#gradute >> 2
#pg >> 3
#PHD>> 4

In [62]:
from sklearn.preprocessing import OrdinalEncoder
df =pd.DataFrame({"qualification": ["HS","PG","GR","HS","PHD","HS","PG"]})

In [63]:
df

qualification
0            HS
1            PG
2            GR
3            HS
4           PHD
5            HS
6            PG

In [64]:
encoder=OrdinalEncoder(categories=[["HS","GR","PG","PHD"]])

In [67]:
encoder.fit_transform(df[['qualification']])


array([[0.],
       [2.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.]])

In [68]:
df

qualification
0            HS
1            PG
2            GR
3            HS
4           PHD
5            HS
6            PG

In [69]:
#top 5/top 10 >> atleast 70 & 80 % of the categorical column captured
df.qualification.value_counts()

qualification
HS     3
PG     2
GR     1
PHD    1
Name: count, dtype: int64

In [70]:
# target guided ordinal encoding
#relation with target variable
#A lot of unique categories
#replace with mean and median

In [75]:
df=pd.DataFrame({'time':['lunch','breakfast','dinner','lunch','breakfast','dinner','lunch','breakfast','dinner'],
              'total_bill':[120,120,40,150,160,130,40,150,160]})

In [76]:
df

time  total_bill
0      lunch         120
1  breakfast         120
2     dinner          40
3      lunch         150
4  breakfast         160
5     dinner         130
6      lunch          40
7  breakfast         150
8     dinner         160

In [77]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [78]:
mean_price

{'breakfast': 143.33333333333334, 'dinner': 110.0, 'lunch': 103.33333333333333}

In [79]:
df['time'].map(mean_price)

0    103.333333
1    143.333333
2    110.000000
3    103.333333
4    143.333333
5    110.000000
6    103.333333
7    143.333333
8    110.000000
Name: time, dtype: float64

In [80]:
df['time_target_encoded']=df['time'].map(mean_price)

In [81]:
df['time_target_encoded']

0    103.333333
1    143.333333
2    110.000000
3    103.333333
4    143.333333
5    110.000000
6    103.333333
7    143.333333
8    110.000000
Name: time_target_encoded, dtype: float64

In [82]:
df

time  total_bill  time_target_encoded
0      lunch         120           103.333333
1  breakfast         120           143.333333
2     dinner          40           110.000000
3      lunch         150           103.333333
4  breakfast         160           143.333333
5     dinner         130           110.000000
6      lunch          40           103.333333
7  breakfast         150           143.333333
8     dinner         160           110.000000

In [83]:
import seaborn as sns
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]