In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [24]:
from sklearn.datasets import make_regression
X,y=make_regression(n_samples=1000,n_features=3,noise=3,random_state=1)

In [25]:
X

array([[ 1.45167891,  0.3416886 , -0.12517266],
       [-0.7003985 , -0.20339445,  0.24266944],
       [-0.10646012, -2.79099641, -0.45611756],
       ...,
       [-0.56282904, -1.2514994 ,  1.29857162],
       [-1.16896134, -1.8994631 , -2.5399554 ],
       [ 0.88608992,  0.31897183,  0.26486763]])

In [26]:
y

array([ 1.39904571e+02, -5.73895194e+01, -2.96893724e+02,  7.21170194e+01,
        5.04726714e+01,  1.57200504e+02,  2.04260303e+02,  2.45152715e+01,
       -4.40087255e+02, -1.69425107e+02,  5.28891813e+01,  2.07289193e+02,
       -9.37774659e+01,  9.35903925e+01, -2.96302269e+02,  7.53450451e+01,
       -1.47200527e+02,  1.14678762e+02,  1.23527566e+02, -1.40769533e+02,
       -1.78451948e+02,  1.22263134e+02, -1.79314709e+01, -8.10963909e+01,
       -6.99232689e+01, -1.53279905e+02,  1.92297657e+02,  2.07265941e+01,
       -8.11609653e+01, -9.59671992e+01,  1.55804815e+02, -7.75749150e+01,
       -8.48911930e+01,  8.07143772e+01,  2.37712896e+02, -2.38146151e+02,
        2.98373697e+02, -4.62391257e+01,  2.51304584e+02,  1.75129670e+02,
       -1.45707642e+00, -3.00146368e+02, -2.62857003e+02,  1.67565370e+01,
        1.47162845e+02, -5.80689227e+01, -1.22442048e+01,  3.53504499e+02,
       -8.09951545e+01,  3.62727381e+01, -2.03157268e+01,  1.77507056e+02,
        6.75353132e+01,  

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test,=train_test_split(X,y,test_size=0.3,random_state=1)


In [28]:
X_train.shape,y_train.shape

((700, 3), (700,))

In [44]:
from sklearn.neighbors import KNeighborsRegressor
reg=KNeighborsRegressor()

In [45]:
reg

KNeighborsRegressor()

In [48]:
reg.fit(X_train,y_train)

KNeighborsRegressor()

In [49]:
y_pred=reg.predict(X_train)

In [50]:
y_pred

array([ 8.45297852e+01, -2.19233885e+02, -2.47705106e+01, -1.37735933e+02,
       -3.33758791e+01, -1.45225414e+02, -1.70489108e+02, -1.41235178e+01,
       -8.95601702e+01, -1.66559679e+01, -1.26632196e+00, -7.84796915e+00,
        2.20179444e+02,  4.26233216e+02,  1.11604363e+02, -2.19000616e+01,
        1.16958518e+02, -5.78683252e+00,  2.52120292e+02, -1.50291515e+02,
        1.08607557e+01, -2.51661328e+02,  4.30718591e+01,  1.10488777e+02,
        1.36972411e+02,  2.14644438e+02, -7.41358934e+01,  1.26528119e+02,
       -1.41365313e+02, -4.23039058e+01,  7.47049948e+01, -1.35302859e+02,
        1.19235993e+02, -2.13245735e+02,  1.01199190e+01, -1.15302617e+02,
        1.47392080e+01, -5.26857213e+01, -2.18934083e+02,  6.91944886e+01,
        7.10591758e+01, -1.95403552e+02, -1.13896939e+02,  1.05080995e+02,
        1.77999380e+02,  6.97918619e+00,  5.52948695e+01, -8.50323076e+01,
       -5.60089637e+01,  9.81199241e+01,  1.87079775e+02,  1.03275363e+02,
        1.65607181e+02, -

In [32]:
params_grid={"n_nebihours":[3,5,6,7,10,12,15],
             'algrothims':['ball tree','brute','kd tree'],
             'leaf_size':20}

In [33]:
params_grid

{'n_nebihours': [3, 5, 6, 7, 10, 12, 15],
 'algrothims': ['ball tree', 'brute', 'kd tree'],
 'leaf_size': 20}

In [34]:
params_grid

{'n_nebihours': [3, 5, 6, 7, 10, 12, 15],
 'algrothims': ['ball tree', 'brute', 'kd tree'],
 'leaf_size': 20}

In [35]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=clf,param_grid=params_grid,cv=5,verbose=5)
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algrothims': ['ball tree', 'brute', 'kd tree'],
                         'leaf_size': 20,
                         'n_nebihours': [3, 5, 6, 7, 10, 12, 15]},
             verbose=5)

In [36]:
#KNN as missing value treatment



In [37]:
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,4,3],[np.nan,6,5],[8,8,7]]
impute=KNNImputer(n_neighbors=2)
impute.fit_transform(X)
array=([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])


In [38]:
X

[[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]

In [39]:
impute=KNNImputer(n_neighbors=2)
impute.fit_transform(X)


array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])